# Generated by Django 3.2.8 on 2021-11-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_derivatives', '0002_auto_20210726_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
