# Generated by Django 4.0.10 on 2024-10-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_derivatives', '0003_bag_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='origin',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('legacy_digital', 'Legacy Digital Processing'), ('digitization', 'Digitization'), ('av_digitization', 'Audiovisual Digitization')], default='aurora', max_length=20),
        ),
    ]
